---
- hosts: all
  tasks:
    - name: Hot patch redis-server service for docker operation (Debian)
      copy:
        src: debian-redis-server.service
        dest: /etc/systemd/system/redis-server.service
      when: ansible_distribution == "Debian"

    - name: Ensure dnf is not installed, which would conflict with ansible-pulp-rpm
      yum:
        name:
          - python2-dnf
          - python2-libdnf
          - dnf-data
          - libdnf
        state: absent
        use_backend: yum
      when:
        - ansible_os_family == "RedHat"
        - ansible_distribution_major_version|int == 7

    # The task to add the repo doesn't upgrade it, so we have to remove it.
    - name: Remove old pulpcore package repo
      file:
        path: /etc/yum.repos.d/pulpcore.repo
        state: absent
