---
name: Pulp Containers
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: '10 3 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2.3.1
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install ansible
        run: |
          pip install --upgrade pip
          sudo apt remove ansible
          pip install -U wheel ansible docker six
          ansible-galaxy collection install --force community.docker
          ansible --version
      - name: Build image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          ansible-playbook ./.github/build_container.yaml
